
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "dddd@dddd.com",
    "password": "dddddd"
}

###
POST http://localhost:3000/auth/signout

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "dddd@dddd.com",
    "password": "dddddd"
}

###
GET http://localhost:3000/auth/whoami

###
GET http://localhost:3000/auth/5

###

GET http://localhost:3000/auth?email=aaaa@aaaa.com

###
DELETE http://localhost:3000/auth/1

###
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "bbbb@bbbb.com"
}

###
GET http://localhost:3000/auth/colors/blue

###
GET http://localhost:3000/auth/colors